spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL

#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL=DEBUG
#
#    type:
#      descriptor:
#        sql:
#          BasicBinder=TRACE


